### ISSUE TITLE
大爹，报错了(呜呜呜)，求解决

### ISSUE THREAD

**Issue by zjhzjhhh** [depycode/burpsuite_hack#18]
报的错误是这个
![image](https://user-images.githubusercontent.com/64487620/230819116-d17a0a50-2861-4bd9-a4e5-df0f5c753217.png)

我的jython是2.7.3版本 
![image](https://user-images.githubusercontent.com/64487620/230819136-34a53826-e4bd-4bc2-867f-2f8642bc8d27.png)

一开始导入的时候提示编码有问题然后我在代码里面加了个encoding
![image](https://user-images.githubusercontent.com/64487620/230819248-319c4c5b-5ef6-4fd1-ab30-1b49cd2f1e77.png)

再导入就是第一个图片报错

求大爹解决 呜呜呜呜呜

**Comment by depycode** [comment]
# 使用方法
- burpsuite 插件加载：BurpExtender_ALL_UI.py ，修改socks host、port 为扫描端对应的ip和端口，然后点击set
![image](https://github.com/depycode/burpsuite_hack/blob/master/p1.png)
![image](https://github.com/depycode/burpsuite_hack/blob/master/p4.png)

- 扫描端启动
```
nohup python3 MyUDPHandler_Threads.py &
```
