### ISSUE TITLE
lz

### ISSUE THREAD

**Issue by epony4c** [depycode/burpsuite_hack#2]
大佬，这个怎么看是不是在检测中啊？
![image](https://user-images.githubusercontent.com/17228839/221781306-1390a96c-8cce-4ab1-b099-a6ef711f3ab6.png)
直接从数据库中看检测结果吗？

**Comment by depycode** [comment]
BurpExtender_ALL.py  里面的 self.scan_host 为需要扫描的根域名。
探测到漏洞会在reports 目录里面生成报告。（会存在误报情况）

**Comment by epony4c** [comment]
如果self.scan_host为空的话，是不是检测所有的域名？还有如果是IP地址的情况下呢？

**Comment by epony4c** [comment]
tql
