### ISSUE TITLE
为什么修改了允许扫描的域名但是还是扫的qq.com

### ISSUE THREAD

**Issue by 978072715** [depycode/burpsuite_hack#24]
![image](https://user-images.githubusercontent.com/67203773/233823807-5c907736-3b8f-494c-92fd-db1abd289e70.png)

**Comment by depycode** [comment]
使用 https://github.com/depycode/burpsuite_hack/blob/master/burpclient/BurpExtender_ALL_UI.py

**Comment by 978072715** [comment]
大佬光加载burp加载BurpExtender_ALL_UI模块的话 扫描脚本没反应
![image](https://user-images.githubusercontent.com/67203773/233825491-3386f30f-97b8-4514-8a30-4fa9d61f2bb9.png)

**Comment by depycode** [comment]
配置好后，点击set

**Comment by 978072715** [comment]
点击了set但是没用

**Comment by depycode** [comment]
再试试。应该不会这样

**Comment by evi1hack** [comment]
@depycode  师傅 我的扫描探测目标都是IP，那 `scan_host` 应该设置为啥啊？  我设置 `*` 点击 set 后，也是没有反应。
![image](https://user-images.githubusercontent.com/16398717/233998241-96260e62-3f15-4a70-a508-57f7c2504235.png)
![image](https://user-images.githubusercontent.com/16398717/233998375-5fa7685f-5a26-4987-92e9-fa1f130149cc.png)
![image](https://user-images.githubusercontent.com/16398717/233998487-aa782abf-7338-4676-b6c9-55613e8ce171.png)

**Comment by depycode** [comment]
设置成0|1|2|3|4|5|6|7|8|9

**Comment by 978072715** [comment]
好的 谢谢大佬 需要先配置目标再启动扫描
![image](https://user-images.githubusercontent.com/67203773/234165275-3074c946-6c4d-42cb-a81f-80a2f9484534.png)
