### ISSUE TITLE
误报太高，怎么添加师傅微信

### ISSUE THREAD

**Issue by DatangST** [depycode/burpsuite_hack#25]
误报太高，怎么添加师傅微信

**Comment by depycode** [comment]
慢慢调优

**Comment by DatangST** [comment]
类似在order by报错很高。而且我在很多加密场景他稍微有变化立马就会检测出漏洞。需要加个逻辑判断if payload=1     ret=true and p=11111111111111111111111111111111111111111111111111111111111 ret =false   pass....。我觉得师傅还可以加一些除开盲注检测之外的东西。类似xia_sql的结合。

**Comment by depycode** [comment]
这种已在优化中

**Comment by DatangST** [comment]
不知道是不是加了师傅，似乎微信上的名字一直没回消息




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月25日(星期二) 中午11:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [depycode/burpsuite_hack] 误报太高，怎么添加师傅微信 (Issue #25)





 
这种已在优化中

**Comment by depycode** [comment]
应该不是我

**Comment by hackd0g** [comment]
bool盲注的误报更高师傅 我感觉需要对页面返回内容做判断 有时候响应头会有变动 然后就判断注入了

**Comment by depycode** [comment]
应该是页面有随机内容返回。

**Comment by depycode** [comment]
把随机的字符干扰通过正则表达式替换掉

**Comment by hackd0g** [comment]
> 应该是页面有随机内容返回。

是的  有些页面响应头有X-Readtime返回 有些有什么trace-id 返回  误报就很大

**Comment by depycode** [comment]
不会比对响应头

**Comment by hackd0g** [comment]
> 不会比对响应头

没去看代码 但是有时候响应的content-length的长度一样 也会判定为注入

**Comment by depycode** [comment]
通过正则把干扰项排除
