### ISSUE TITLE
ssrf扫描问题

### ISSUE THREAD

**Issue by Explore-c** [depycode/burpsuite_hack#29]
ssrf扫描好像有点问题，我没配置key，直接配置dnslog地址的，地址是这个：`http://dnslog.pw/`
会重复扫描，连sql注入都会重复扫描dnslog地址
![image](https://user-images.githubusercontent.com/46821530/236141155-eb1c73f0-d2ce-4b8c-9541-ed8a1d64c052.png)
扫一次两百多条记录
![image](https://user-images.githubusercontent.com/46821530/236141445-1b07ff6e-bdbd-4c86-a075-0ea1569e9dc3.png)

**Comment by depycode** [comment]
没有遇到
