### ISSUE TITLE
加载插件遇到一个报错，大师傅看看

### ISSUE THREAD

**Issue by eeeeeeeeee-code** [depycode/burpsuite_hack#32]
burp加载插件遇到错误加载不了，英文目录，杀毒没有杀东西，jython换了2.7的和2.5的都不可以
![图片](https://github.com/depycode/burpsuite_hack/assets/115862499/3ec4d35e-f77b-47f6-8ca7-d1d1d134d6c6)
![图片](https://github.com/depycode/burpsuite_hack/assets/115862499/8fad9299-8a92-44f5-9e32-3e92b6b10fb7)

**Comment by jinzezhi** [comment]
师傅这个是怎么解决的呀 我也遇到这个问题
