### ISSUE TITLE
师傅搭建好没反应，能否出个详细点的搭建教程

### ISSUE THREAD

**Issue by B1gd0g** [depycode/burpsuite_hack#4]

**Comment by depycode** [comment]
用 BurpExtender_ALL_UI.py

**Comment by B1gd0g** [comment]
是用的BurpExtender_ALL_UI.py，服务端怎么搭建好？我在服务器上搭建的服务端，BurpExtender_ALL_UI.py代理端口也配置了，数据库也配置了，没流量过去

**Comment by depycode** [comment]
在 SCAN_HOST 范围内的域名请求才会发送到服务端。
