### ISSUE TITLE
dnslog用的哪个项目搭建

### ISSUE THREAD

**Issue by okoling** [depycode/burpsuite_hack#6]
工具很赞！
请问下dnslog用的哪个项目搭建~
还有就是跑出来的结果：
![image](https://user-images.githubusercontent.com/90396284/224492083-ce5401fb-bf65-43fc-ad55-b90be5815d20.png)
确定是根据页面相似度在值区间吗，有一些测试案例演示吗

**Comment by depycode** [comment]
有提供接口查询的dnslog平台都可以
