### ISSUE TITLE
运行一直出现一个error

### ISSUE THREAD

**Issue by DatangST** [depycode/burpsuite_hack#8]
self.port = int(Config.get_instance().get('mysql.PORT'))
![image](https://user-images.githubusercontent.com/52750566/225339189-7e2324bf-e896-4782-9a39-860055240578.png)

**Comment by depycode** [comment]
{} 都要去掉啊，改成你的

**Comment by DatangST** [comment]
可以加一下师傅的V嘛，在测试中出现了一个检测但是一直没出来结果

**Comment by depycode** [comment]
是确认是漏洞但是扫描器没检测到吗

**Comment by DatangST** [comment]
是的，很多情况
